# Generated by Django 4.1.1 on 2022-11-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('louslist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='color',
            field=models.CharField(default='#000000', max_length=8),
        ),
        migrations.AddField(
            model_name='schedule',
            name='name',
            field=models.CharField(default='schedule', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='semester',
            field=models.IntegerField(default=1228),
            preserve_default=False,
        ),
    ]
