# Generated by Django 4.1.1 on 2022-11-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('louslist', '0003_schedule_date_created_user_grad_year_user_major_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.CharField(default='profile.png', max_length=255),
        ),
    ]
