# Generated by Django 4.1.1 on 2022-11-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('louslist', '0008_rename_searchterms_searchterm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
